/**
 * The number of messages to translate in each batch.
 */
export const TRANSLATION_BATCH_SIZE = 100;

/**
 * Mapping of language codes to human-readable language names.
 * Used to provide better context to the AI model in translation prompts.
 */
export const LANGUAGE_NAMES: Record<string, string> = {
	de: 'German',
	fr: 'French',
	es: 'Spanish',
	it: 'Italian',
	pt: 'Portuguese',
	nl: 'Dutch',
	pl: 'Polish',
	ja: 'Japanese',
	zh: 'Chinese (Simplified)',
	ko: 'Korean',
	ru: 'Russian',
	tr: 'Turkish',
	ar: 'Arabic',
};

/**
 * Revision error types representing different categories of issues.
 * Used to categorize suggestions when revising localization content.
 */
export const REVISION_ERROR_TYPES = {
	spelling: {
		label: 'Spelling',
		description: 'Typos and spelling mistakes',
	},
	grammar: {
		label: 'Grammar',
		description: 'Grammar errors such as wrong verb forms, subject-verb agreement, or incorrect tense',
	},
	inconsistency: {
		label: 'Inconsistencies',
		description: 'Inconsistencies such as mixed American and British English — report as one suggestion per inconsistency, not per occurrence',
	},
	wordiness: {
		label: 'Wordiness',
		description: 'Redundant words, overly complicated phrases, or sentences that are not straight to the point',
	},
	'ai-tone': {
		label: 'AI Tone',
		description: 'Text that sounds like it was generated by an LLM, e.g. em-dashes, "leverage", "utilize", "delve", "seamlessly", or hedging phrases like "It\'s important to note that"',
	},
	ambiguity: {
		label: 'Ambiguity',
		description: 'Labels, headings, or text whose meaning is unclear or ambiguous in context — must include a concrete reason',
	},
	seo: {
		label: 'SEO',
		description: 'Simple changes to improve search engine discoverability — must include a concrete reason',
	},
	geo: {
		label: 'GEO',
		description: 'Simple changes to improve how the content is understood and surfaced by LLM-based answer engines and AI crawlers — must include a concrete reason',
	},
} as const;

/**
 * Valid revision error type identifiers.
 */
export type RevisionErrorType = keyof typeof REVISION_ERROR_TYPES;

/**
 * The number of messages to analyze in each revision batch.
 */
export const REVISION_BATCH_SIZE = 100;

