import {LANGUAGE_NAMES, REVISION_ERROR_TYPES, type RevisionErrorType} from './consts.js';

/**
 * Builds the prompt for website advising using URL context.
 * @param errorTypes - Array of error types to check for
 * @param websiteUrl - The URL of the website to analyze
 * @returns The prompt string
 */
export function buildAdviseWebsitePrompt(errorTypes: RevisionErrorType[], websiteUrl: string): string {
	const typeBlocks: Record<RevisionErrorType, string> = {
		spelling: `- spelling: Typos and spelling mistakes.
  Example: "recieve" → "receive"
  Not: stylistic spelling choices like "grey" vs "gray" (that's an inconsistency)`,
		grammar: `- grammar: Grammar errors such as wrong verb forms, subject-verb agreement, or incorrect tense.
  Example: "We helps you build" → "We help you build"
  Not: stylistic choices like Oxford comma usage`,
		inconsistency: `- inconsistency: Inconsistencies such as mixed American and British English. Report as ONE suggestion per inconsistency, not per occurrence. List all occurrences in the reason.
  Example: Page mixes "colour" and "color" → suggest picking one convention
  Not: different wording styles across sections (that's normal for different contexts)`,
		wordiness: `- wordiness: Redundant words, overly complicated phrases, or sentences that are not straight to the point.
  Example: "In order to get started with the process" → "To get started"
  Not: intentionally detailed legal or compliance text`,
		'ai-tone': `- ai-tone: Text that reads like it was generated by an LLM — em-dashes, "leverage", "utilize", "delve", "seamlessly", hedging phrases like "It's important to note that".
  Example: "Leverage our cutting-edge solution to seamlessly optimize" → "Use our solution to improve"
  Not: technical terms that happen to be formal`,
		ambiguity: `- ambiguity: Labels, headings, or text whose meaning is unclear or ambiguous in the context of the page. Must include a concrete reason.
  Example: Button labelled "Submit" on a page with multiple forms — unclear which action it triggers
  Not: copy that is clear but could theoretically be rephrased`,
		seo: `- seo: Simple changes to improve search engine discoverability. Must include a concrete reason.
  Example: Generic heading "Our Services" → "Web Design & Development Services"
  Not: keyword-stuffing or rewriting entire paragraphs`,
		geo: `- geo: Simple changes to improve how the content is understood and surfaced by LLM-based answer engines and AI crawlers. Must include a concrete reason.
  Example: Vague paragraph "We offer many solutions" → "We offer website design, hosting, and SEO consulting" — specific claims are easier for LLMs to extract and cite
  Not: adding structured data or schema markup (that's not visible text)`,
	};

	const typeDescriptions = errorTypes.map(type => typeBlocks[type]).join('\n\n');

	return `You are a UX writing expert specializing in website copy and interface labels.

Visit this website and analyze its visible text content: ${websiteUrl}

Only analyze text that is directly visible to the user on the page. This includes headings, paragraphs, buttons, links, navigation items, form labels, and placeholders.

Do NOT analyze or report issues in hidden or non-rendered text such as image alt attributes, meta descriptions, page titles, aria-labels, HTML comments, or any other text that is not visually displayed on the page.

Find issues in the following categories:

${typeDescriptions}

Important guidelines:
- Only report actual issues, not stylistic preferences
- Suggest improvements that match the website's tone and purpose
- Be concise in your reasoning
- Use a descriptive key for each issue (e.g., "heading-1", "nav-about", "button-submit")
- Sort results by severity (high first), then group by error type within each severity level

Respond with ONLY a JSON array of objects, each with these fields:
- "key": descriptive label key
- "section": short description of where on the page the issue is found (e.g., "Hero section", "Navigation", "Footer", "Pricing table")
- "original": the original text
- "suggested": your suggested replacement
- "reason": brief explanation
- "type": one of ${errorTypes.map(t => `"${t}"`).join(', ')}
- "severity": one of "high", "medium", "low", or "very low" — rate how important this fix is

If there are no issues, respond with an empty array: []`;
}

/**
 * Builds the system prompt for translation.
 * @param targetLanguage - The target language code
 * @param context - Optional product context
 * @returns The system prompt string
 */
export function buildSystemPrompt(targetLanguage: string, context: string): string {
	const targetLangName = LANGUAGE_NAMES[targetLanguage] ?? targetLanguage;

	let prompt = `You are a professional translator specializing in software localization. 
Translate the following UI text from English to ${targetLangName}.

Important guidelines:
- Preserve any placeholders like {name}, {count}, {{variable}}, etc.
- Keep the same tone and formality level
- Use natural, idiomatic expressions in the target language
- Maintain any HTML tags or markdown formatting
- Do not add or remove content, only translate`;

	if (context) {
		prompt += `\n\nProduct context for better translations:\n${context}`;
	}

	return prompt;
}

/**
 * Builds the full translation prompt for a batch of messages.
 * @param systemPrompt - The system prompt from buildSystemPrompt
 * @param batch - Array of [key, value] entries to translate
 * @returns The complete prompt string
 */
export function buildTranslationPrompt(systemPrompt: string, batch: Array<[string, string]>): string {
	return `${systemPrompt}

Translate each of the following messages:

${JSON.stringify(Object.fromEntries(batch), null, 2)}`;
}

/**
 * Builds the system prompt for revision/proofreading.
 * @param errorTypes - Array of error types to check for
 * @param context - Optional product context
 * @returns The system prompt string
 */
export function buildRevisionSystemPrompt(errorTypes: RevisionErrorType[], context: string): string {
	const typeDescriptions = errorTypes.map(type => {
		const info = REVISION_ERROR_TYPES[type];
		return `- ${type}: ${info.description}`;
	}).join('\n');

	let prompt = `You are a professional editor and proofreader specializing in software localization content.
Analyze the following UI text and find issues that need improvement.

You should look for these types of issues:
${typeDescriptions}

Important guidelines:
- Only report actual issues, not stylistic preferences
- Preserve any placeholders like {name}, {count}, {{variable}}, etc.
- Maintain any HTML tags or markdown formatting
- Provide clear, actionable suggestions
- Be concise in your reasoning`;

	if (context) {
		prompt += `\n\nProduct context for better understanding:\n${context}`;
	}

	return prompt;
}

/**
 * Builds the full revision prompt for a batch of messages.
 * @param systemPrompt - The system prompt from buildRevisionSystemPrompt
 * @param batch - Array of [key, value] entries to revise
 * @returns The complete prompt string
 */
export function buildRevisionPrompt(systemPrompt: string, batch: Array<[string, string]>): string {
	return `${systemPrompt}

Analyze each of the following messages and return a JSON array of suggestions.
For each issue found, include: the message key, the original text, your suggested fix, a brief reason, and the error type.
If a message has no issues, do not include it in the output.

Messages to analyze:

${JSON.stringify(Object.fromEntries(batch), null, 2)}`;
}
